// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKrQcIvmo4RpVOn2v7urqWe0qO1ShZiNc',
    appId: '1:30153363439:web:068e9921261482dcbf301a',
    messagingSenderId: '30153363439',
    projectId: 'elegantia-a34c2',
    authDomain: 'elegantia-a34c2.firebaseapp.com',
    storageBucket: 'elegantia-a34c2.firebasestorage.app',
    measurementId: 'G-V0PQLB2XQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUaMkTkJDuK6mUgd3zCirAG88_dika2Eg',
    appId: '1:30153363439:android:33c2aeb81e1f2621bf301a',
    messagingSenderId: '30153363439',
    projectId: 'elegantia-a34c2',
    storageBucket: 'elegantia-a34c2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKrQcIvmo4RpVOn2v7urqWe0qO1ShZiNc',
    appId: '1:30153363439:web:fc2b53f22abaa1c5bf301a',
    messagingSenderId: '30153363439',
    projectId: 'elegantia-a34c2',
    authDomain: 'elegantia-a34c2.firebaseapp.com',
    storageBucket: 'elegantia-a34c2.firebasestorage.app',
    measurementId: 'G-FRG8XWF5T0',
  );
}
